#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/josediaz/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
idesk &
xset off off &
xset -dpms &
udiskie &
udevil &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.
setxkbmap -layout latam &
nitrogen --restore &
volumeicon &
nm-applet &
flameshot &
dunst &
exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/josediaz/.fluxbox/log"
